---
- name: Change ownership of WordPress installation
  file: >
    path="{{ wp_deployment_directory_root }}"
    owner="{{ replication_username }}"
    group="{{ replication_username }}"
    state=directory
    recurse=yes

