---
- name: Allow traffic on the reverse proxy port
  ufw: rule=allow port={{ reverse_proxy_port }}
- include: directory_structure.yml
- include: ssh.yml
- include: replication.yml
  when: replicator
- include: deploy.yml
  when: replicator
- include: restart.yml
